// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: transaction.proto

package testtask.avast.budgetbuddy.utils;

public final class Proto {
  private Proto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface TransactionOrBuilder extends
      // @@protoc_insertion_point(interface_extends:testtask.avast.budgetbuddy.utils.Transaction)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>optional string guid = 1;</code>
     */
    boolean hasGuid();
    /**
     * <code>optional string guid = 1;</code>
     */
    java.lang.String getGuid();
    /**
     * <code>optional string guid = 1;</code>
     */
    com.google.protobuf.ByteString
        getGuidBytes();

    /**
     * <code>optional int64 date = 2;</code>
     */
    boolean hasDate();
    /**
     * <code>optional int64 date = 2;</code>
     */
    long getDate();

    /**
     * <code>optional double value = 3;</code>
     */
    boolean hasValue();
    /**
     * <code>optional double value = 3;</code>
     */
    double getValue();

    /**
     * <code>optional string kind = 4;</code>
     */
    boolean hasKind();
    /**
     * <code>optional string kind = 4;</code>
     */
    java.lang.String getKind();
    /**
     * <code>optional string kind = 4;</code>
     */
    com.google.protobuf.ByteString
        getKindBytes();

    /**
     * <code>optional bool deleted = 5;</code>
     */
    boolean hasDeleted();
    /**
     * <code>optional bool deleted = 5;</code>
     */
    boolean getDeleted();
  }
  /**
   * Protobuf type {@code testtask.avast.budgetbuddy.utils.Transaction}
   */
  public static final class Transaction extends
      com.google.protobuf.GeneratedMessageLite implements
      // @@protoc_insertion_point(message_implements:testtask.avast.budgetbuddy.utils.Transaction)
      TransactionOrBuilder {
    // Use Transaction.newBuilder() to construct.
    private Transaction(com.google.protobuf.GeneratedMessageLite.Builder builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Transaction(boolean noInit) { this.unknownFields = com.google.protobuf.ByteString.EMPTY;}

    private static final Transaction defaultInstance;
    public static Transaction getDefaultInstance() {
      return defaultInstance;
    }

    public Transaction getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.ByteString unknownFields;
    private Transaction(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.ByteString.Output unknownFieldsOutput =
          com.google.protobuf.ByteString.newOutput();
      com.google.protobuf.CodedOutputStream unknownFieldsCodedOutput =
          com.google.protobuf.CodedOutputStream.newInstance(
              unknownFieldsOutput);
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFieldsCodedOutput,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              guid_ = bs;
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              date_ = input.readInt64();
              break;
            }
            case 25: {
              bitField0_ |= 0x00000004;
              value_ = input.readDouble();
              break;
            }
            case 34: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000008;
              kind_ = bs;
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              deleted_ = input.readBool();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        try {
          unknownFieldsCodedOutput.flush();
        } catch (java.io.IOException e) {
        // Should not happen
        } finally {
          unknownFields = unknownFieldsOutput.toByteString();
        }
        makeExtensionsImmutable();
      }
    }
    public static com.google.protobuf.Parser<Transaction> PARSER =
        new com.google.protobuf.AbstractParser<Transaction>() {
      public Transaction parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Transaction(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Transaction> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int GUID_FIELD_NUMBER = 1;
    private java.lang.Object guid_;
    /**
     * <code>optional string guid = 1;</code>
     */
    public boolean hasGuid() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string guid = 1;</code>
     */
    public java.lang.String getGuid() {
      java.lang.Object ref = guid_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          guid_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string guid = 1;</code>
     */
    public com.google.protobuf.ByteString
        getGuidBytes() {
      java.lang.Object ref = guid_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        guid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DATE_FIELD_NUMBER = 2;
    private long date_;
    /**
     * <code>optional int64 date = 2;</code>
     */
    public boolean hasDate() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int64 date = 2;</code>
     */
    public long getDate() {
      return date_;
    }

    public static final int VALUE_FIELD_NUMBER = 3;
    private double value_;
    /**
     * <code>optional double value = 3;</code>
     */
    public boolean hasValue() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional double value = 3;</code>
     */
    public double getValue() {
      return value_;
    }

    public static final int KIND_FIELD_NUMBER = 4;
    private java.lang.Object kind_;
    /**
     * <code>optional string kind = 4;</code>
     */
    public boolean hasKind() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional string kind = 4;</code>
     */
    public java.lang.String getKind() {
      java.lang.Object ref = kind_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          kind_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string kind = 4;</code>
     */
    public com.google.protobuf.ByteString
        getKindBytes() {
      java.lang.Object ref = kind_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        kind_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DELETED_FIELD_NUMBER = 5;
    private boolean deleted_;
    /**
     * <code>optional bool deleted = 5;</code>
     */
    public boolean hasDeleted() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional bool deleted = 5;</code>
     */
    public boolean getDeleted() {
      return deleted_;
    }

    private void initFields() {
      guid_ = "";
      date_ = 0L;
      value_ = 0D;
      kind_ = "";
      deleted_ = false;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getGuidBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt64(2, date_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeDouble(3, value_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getKindBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBool(5, deleted_);
      }
      output.writeRawBytes(unknownFields);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getGuidBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, date_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(3, value_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getKindBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(5, deleted_);
      }
      size += unknownFields.size();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static testtask.avast.budgetbuddy.utils.Proto.Transaction parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static testtask.avast.budgetbuddy.utils.Proto.Transaction parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static testtask.avast.budgetbuddy.utils.Proto.Transaction parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static testtask.avast.budgetbuddy.utils.Proto.Transaction parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static testtask.avast.budgetbuddy.utils.Proto.Transaction parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static testtask.avast.budgetbuddy.utils.Proto.Transaction parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static testtask.avast.budgetbuddy.utils.Proto.Transaction parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static testtask.avast.budgetbuddy.utils.Proto.Transaction parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static testtask.avast.budgetbuddy.utils.Proto.Transaction parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static testtask.avast.budgetbuddy.utils.Proto.Transaction parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(testtask.avast.budgetbuddy.utils.Proto.Transaction prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    /**
     * Protobuf type {@code testtask.avast.budgetbuddy.utils.Transaction}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          testtask.avast.budgetbuddy.utils.Proto.Transaction, Builder>
        implements
        // @@protoc_insertion_point(builder_implements:testtask.avast.budgetbuddy.utils.Transaction)
        testtask.avast.budgetbuddy.utils.Proto.TransactionOrBuilder {
      // Construct using testtask.avast.budgetbuddy.utils.Proto.Transaction.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private void maybeForceBuilderInitialization() {
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        guid_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        date_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        value_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000004);
        kind_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        deleted_ = false;
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public testtask.avast.budgetbuddy.utils.Proto.Transaction getDefaultInstanceForType() {
        return testtask.avast.budgetbuddy.utils.Proto.Transaction.getDefaultInstance();
      }

      public testtask.avast.budgetbuddy.utils.Proto.Transaction build() {
        testtask.avast.budgetbuddy.utils.Proto.Transaction result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public testtask.avast.budgetbuddy.utils.Proto.Transaction buildPartial() {
        testtask.avast.budgetbuddy.utils.Proto.Transaction result = new testtask.avast.budgetbuddy.utils.Proto.Transaction(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.guid_ = guid_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.date_ = date_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.value_ = value_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.kind_ = kind_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.deleted_ = deleted_;
        result.bitField0_ = to_bitField0_;
        return result;
      }

      public Builder mergeFrom(testtask.avast.budgetbuddy.utils.Proto.Transaction other) {
        if (other == testtask.avast.budgetbuddy.utils.Proto.Transaction.getDefaultInstance()) return this;
        if (other.hasGuid()) {
          bitField0_ |= 0x00000001;
          guid_ = other.guid_;
          
        }
        if (other.hasDate()) {
          setDate(other.getDate());
        }
        if (other.hasValue()) {
          setValue(other.getValue());
        }
        if (other.hasKind()) {
          bitField0_ |= 0x00000008;
          kind_ = other.kind_;
          
        }
        if (other.hasDeleted()) {
          setDeleted(other.getDeleted());
        }
        setUnknownFields(
            getUnknownFields().concat(other.unknownFields));
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        testtask.avast.budgetbuddy.utils.Proto.Transaction parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (testtask.avast.budgetbuddy.utils.Proto.Transaction) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object guid_ = "";
      /**
       * <code>optional string guid = 1;</code>
       */
      public boolean hasGuid() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string guid = 1;</code>
       */
      public java.lang.String getGuid() {
        java.lang.Object ref = guid_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            guid_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string guid = 1;</code>
       */
      public com.google.protobuf.ByteString
          getGuidBytes() {
        java.lang.Object ref = guid_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          guid_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string guid = 1;</code>
       */
      public Builder setGuid(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        guid_ = value;
        
        return this;
      }
      /**
       * <code>optional string guid = 1;</code>
       */
      public Builder clearGuid() {
        bitField0_ = (bitField0_ & ~0x00000001);
        guid_ = getDefaultInstance().getGuid();
        
        return this;
      }
      /**
       * <code>optional string guid = 1;</code>
       */
      public Builder setGuidBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        guid_ = value;
        
        return this;
      }

      private long date_ ;
      /**
       * <code>optional int64 date = 2;</code>
       */
      public boolean hasDate() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int64 date = 2;</code>
       */
      public long getDate() {
        return date_;
      }
      /**
       * <code>optional int64 date = 2;</code>
       */
      public Builder setDate(long value) {
        bitField0_ |= 0x00000002;
        date_ = value;
        
        return this;
      }
      /**
       * <code>optional int64 date = 2;</code>
       */
      public Builder clearDate() {
        bitField0_ = (bitField0_ & ~0x00000002);
        date_ = 0L;
        
        return this;
      }

      private double value_ ;
      /**
       * <code>optional double value = 3;</code>
       */
      public boolean hasValue() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional double value = 3;</code>
       */
      public double getValue() {
        return value_;
      }
      /**
       * <code>optional double value = 3;</code>
       */
      public Builder setValue(double value) {
        bitField0_ |= 0x00000004;
        value_ = value;
        
        return this;
      }
      /**
       * <code>optional double value = 3;</code>
       */
      public Builder clearValue() {
        bitField0_ = (bitField0_ & ~0x00000004);
        value_ = 0D;
        
        return this;
      }

      private java.lang.Object kind_ = "";
      /**
       * <code>optional string kind = 4;</code>
       */
      public boolean hasKind() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional string kind = 4;</code>
       */
      public java.lang.String getKind() {
        java.lang.Object ref = kind_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            kind_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string kind = 4;</code>
       */
      public com.google.protobuf.ByteString
          getKindBytes() {
        java.lang.Object ref = kind_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          kind_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string kind = 4;</code>
       */
      public Builder setKind(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        kind_ = value;
        
        return this;
      }
      /**
       * <code>optional string kind = 4;</code>
       */
      public Builder clearKind() {
        bitField0_ = (bitField0_ & ~0x00000008);
        kind_ = getDefaultInstance().getKind();
        
        return this;
      }
      /**
       * <code>optional string kind = 4;</code>
       */
      public Builder setKindBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        kind_ = value;
        
        return this;
      }

      private boolean deleted_ ;
      /**
       * <code>optional bool deleted = 5;</code>
       */
      public boolean hasDeleted() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional bool deleted = 5;</code>
       */
      public boolean getDeleted() {
        return deleted_;
      }
      /**
       * <code>optional bool deleted = 5;</code>
       */
      public Builder setDeleted(boolean value) {
        bitField0_ |= 0x00000010;
        deleted_ = value;
        
        return this;
      }
      /**
       * <code>optional bool deleted = 5;</code>
       */
      public Builder clearDeleted() {
        bitField0_ = (bitField0_ & ~0x00000010);
        deleted_ = false;
        
        return this;
      }

      // @@protoc_insertion_point(builder_scope:testtask.avast.budgetbuddy.utils.Transaction)
    }

    static {
      defaultInstance = new Transaction(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:testtask.avast.budgetbuddy.utils.Transaction)
  }

  public interface AccountDeltaOrBuilder extends
      // @@protoc_insertion_point(interface_extends:testtask.avast.budgetbuddy.utils.AccountDelta)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>repeated .testtask.avast.budgetbuddy.utils.Transaction addedOrModified = 1;</code>
     */
    java.util.List<testtask.avast.budgetbuddy.utils.Proto.Transaction> 
        getAddedOrModifiedList();
    /**
     * <code>repeated .testtask.avast.budgetbuddy.utils.Transaction addedOrModified = 1;</code>
     */
    testtask.avast.budgetbuddy.utils.Proto.Transaction getAddedOrModified(int index);
    /**
     * <code>repeated .testtask.avast.budgetbuddy.utils.Transaction addedOrModified = 1;</code>
     */
    int getAddedOrModifiedCount();

    /**
     * <code>optional int64 serverTimestamp = 2;</code>
     */
    boolean hasServerTimestamp();
    /**
     * <code>optional int64 serverTimestamp = 2;</code>
     */
    long getServerTimestamp();
  }
  /**
   * Protobuf type {@code testtask.avast.budgetbuddy.utils.AccountDelta}
   */
  public static final class AccountDelta extends
      com.google.protobuf.GeneratedMessageLite implements
      // @@protoc_insertion_point(message_implements:testtask.avast.budgetbuddy.utils.AccountDelta)
      AccountDeltaOrBuilder {
    // Use AccountDelta.newBuilder() to construct.
    private AccountDelta(com.google.protobuf.GeneratedMessageLite.Builder builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private AccountDelta(boolean noInit) { this.unknownFields = com.google.protobuf.ByteString.EMPTY;}

    private static final AccountDelta defaultInstance;
    public static AccountDelta getDefaultInstance() {
      return defaultInstance;
    }

    public AccountDelta getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.ByteString unknownFields;
    private AccountDelta(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.ByteString.Output unknownFieldsOutput =
          com.google.protobuf.ByteString.newOutput();
      com.google.protobuf.CodedOutputStream unknownFieldsCodedOutput =
          com.google.protobuf.CodedOutputStream.newInstance(
              unknownFieldsOutput);
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFieldsCodedOutput,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                addedOrModified_ = new java.util.ArrayList<testtask.avast.budgetbuddy.utils.Proto.Transaction>();
                mutable_bitField0_ |= 0x00000001;
              }
              addedOrModified_.add(input.readMessage(testtask.avast.budgetbuddy.utils.Proto.Transaction.PARSER, extensionRegistry));
              break;
            }
            case 16: {
              bitField0_ |= 0x00000001;
              serverTimestamp_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          addedOrModified_ = java.util.Collections.unmodifiableList(addedOrModified_);
        }
        try {
          unknownFieldsCodedOutput.flush();
        } catch (java.io.IOException e) {
        // Should not happen
        } finally {
          unknownFields = unknownFieldsOutput.toByteString();
        }
        makeExtensionsImmutable();
      }
    }
    public static com.google.protobuf.Parser<AccountDelta> PARSER =
        new com.google.protobuf.AbstractParser<AccountDelta>() {
      public AccountDelta parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new AccountDelta(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<AccountDelta> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int ADDEDORMODIFIED_FIELD_NUMBER = 1;
    private java.util.List<testtask.avast.budgetbuddy.utils.Proto.Transaction> addedOrModified_;
    /**
     * <code>repeated .testtask.avast.budgetbuddy.utils.Transaction addedOrModified = 1;</code>
     */
    public java.util.List<testtask.avast.budgetbuddy.utils.Proto.Transaction> getAddedOrModifiedList() {
      return addedOrModified_;
    }
    /**
     * <code>repeated .testtask.avast.budgetbuddy.utils.Transaction addedOrModified = 1;</code>
     */
    public java.util.List<? extends testtask.avast.budgetbuddy.utils.Proto.TransactionOrBuilder> 
        getAddedOrModifiedOrBuilderList() {
      return addedOrModified_;
    }
    /**
     * <code>repeated .testtask.avast.budgetbuddy.utils.Transaction addedOrModified = 1;</code>
     */
    public int getAddedOrModifiedCount() {
      return addedOrModified_.size();
    }
    /**
     * <code>repeated .testtask.avast.budgetbuddy.utils.Transaction addedOrModified = 1;</code>
     */
    public testtask.avast.budgetbuddy.utils.Proto.Transaction getAddedOrModified(int index) {
      return addedOrModified_.get(index);
    }
    /**
     * <code>repeated .testtask.avast.budgetbuddy.utils.Transaction addedOrModified = 1;</code>
     */
    public testtask.avast.budgetbuddy.utils.Proto.TransactionOrBuilder getAddedOrModifiedOrBuilder(
        int index) {
      return addedOrModified_.get(index);
    }

    public static final int SERVERTIMESTAMP_FIELD_NUMBER = 2;
    private long serverTimestamp_;
    /**
     * <code>optional int64 serverTimestamp = 2;</code>
     */
    public boolean hasServerTimestamp() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int64 serverTimestamp = 2;</code>
     */
    public long getServerTimestamp() {
      return serverTimestamp_;
    }

    private void initFields() {
      addedOrModified_ = java.util.Collections.emptyList();
      serverTimestamp_ = 0L;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < addedOrModified_.size(); i++) {
        output.writeMessage(1, addedOrModified_.get(i));
      }
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(2, serverTimestamp_);
      }
      output.writeRawBytes(unknownFields);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < addedOrModified_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, addedOrModified_.get(i));
      }
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, serverTimestamp_);
      }
      size += unknownFields.size();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static testtask.avast.budgetbuddy.utils.Proto.AccountDelta parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static testtask.avast.budgetbuddy.utils.Proto.AccountDelta parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static testtask.avast.budgetbuddy.utils.Proto.AccountDelta parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static testtask.avast.budgetbuddy.utils.Proto.AccountDelta parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static testtask.avast.budgetbuddy.utils.Proto.AccountDelta parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static testtask.avast.budgetbuddy.utils.Proto.AccountDelta parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static testtask.avast.budgetbuddy.utils.Proto.AccountDelta parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static testtask.avast.budgetbuddy.utils.Proto.AccountDelta parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static testtask.avast.budgetbuddy.utils.Proto.AccountDelta parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static testtask.avast.budgetbuddy.utils.Proto.AccountDelta parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(testtask.avast.budgetbuddy.utils.Proto.AccountDelta prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    /**
     * Protobuf type {@code testtask.avast.budgetbuddy.utils.AccountDelta}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          testtask.avast.budgetbuddy.utils.Proto.AccountDelta, Builder>
        implements
        // @@protoc_insertion_point(builder_implements:testtask.avast.budgetbuddy.utils.AccountDelta)
        testtask.avast.budgetbuddy.utils.Proto.AccountDeltaOrBuilder {
      // Construct using testtask.avast.budgetbuddy.utils.Proto.AccountDelta.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private void maybeForceBuilderInitialization() {
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        addedOrModified_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        serverTimestamp_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public testtask.avast.budgetbuddy.utils.Proto.AccountDelta getDefaultInstanceForType() {
        return testtask.avast.budgetbuddy.utils.Proto.AccountDelta.getDefaultInstance();
      }

      public testtask.avast.budgetbuddy.utils.Proto.AccountDelta build() {
        testtask.avast.budgetbuddy.utils.Proto.AccountDelta result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public testtask.avast.budgetbuddy.utils.Proto.AccountDelta buildPartial() {
        testtask.avast.budgetbuddy.utils.Proto.AccountDelta result = new testtask.avast.budgetbuddy.utils.Proto.AccountDelta(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          addedOrModified_ = java.util.Collections.unmodifiableList(addedOrModified_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.addedOrModified_ = addedOrModified_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000001;
        }
        result.serverTimestamp_ = serverTimestamp_;
        result.bitField0_ = to_bitField0_;
        return result;
      }

      public Builder mergeFrom(testtask.avast.budgetbuddy.utils.Proto.AccountDelta other) {
        if (other == testtask.avast.budgetbuddy.utils.Proto.AccountDelta.getDefaultInstance()) return this;
        if (!other.addedOrModified_.isEmpty()) {
          if (addedOrModified_.isEmpty()) {
            addedOrModified_ = other.addedOrModified_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureAddedOrModifiedIsMutable();
            addedOrModified_.addAll(other.addedOrModified_);
          }
          
        }
        if (other.hasServerTimestamp()) {
          setServerTimestamp(other.getServerTimestamp());
        }
        setUnknownFields(
            getUnknownFields().concat(other.unknownFields));
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        testtask.avast.budgetbuddy.utils.Proto.AccountDelta parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (testtask.avast.budgetbuddy.utils.Proto.AccountDelta) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<testtask.avast.budgetbuddy.utils.Proto.Transaction> addedOrModified_ =
        java.util.Collections.emptyList();
      private void ensureAddedOrModifiedIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          addedOrModified_ = new java.util.ArrayList<testtask.avast.budgetbuddy.utils.Proto.Transaction>(addedOrModified_);
          bitField0_ |= 0x00000001;
         }
      }

      /**
       * <code>repeated .testtask.avast.budgetbuddy.utils.Transaction addedOrModified = 1;</code>
       */
      public java.util.List<testtask.avast.budgetbuddy.utils.Proto.Transaction> getAddedOrModifiedList() {
        return java.util.Collections.unmodifiableList(addedOrModified_);
      }
      /**
       * <code>repeated .testtask.avast.budgetbuddy.utils.Transaction addedOrModified = 1;</code>
       */
      public int getAddedOrModifiedCount() {
        return addedOrModified_.size();
      }
      /**
       * <code>repeated .testtask.avast.budgetbuddy.utils.Transaction addedOrModified = 1;</code>
       */
      public testtask.avast.budgetbuddy.utils.Proto.Transaction getAddedOrModified(int index) {
        return addedOrModified_.get(index);
      }
      /**
       * <code>repeated .testtask.avast.budgetbuddy.utils.Transaction addedOrModified = 1;</code>
       */
      public Builder setAddedOrModified(
          int index, testtask.avast.budgetbuddy.utils.Proto.Transaction value) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureAddedOrModifiedIsMutable();
        addedOrModified_.set(index, value);

        return this;
      }
      /**
       * <code>repeated .testtask.avast.budgetbuddy.utils.Transaction addedOrModified = 1;</code>
       */
      public Builder setAddedOrModified(
          int index, testtask.avast.budgetbuddy.utils.Proto.Transaction.Builder builderForValue) {
        ensureAddedOrModifiedIsMutable();
        addedOrModified_.set(index, builderForValue.build());

        return this;
      }
      /**
       * <code>repeated .testtask.avast.budgetbuddy.utils.Transaction addedOrModified = 1;</code>
       */
      public Builder addAddedOrModified(testtask.avast.budgetbuddy.utils.Proto.Transaction value) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureAddedOrModifiedIsMutable();
        addedOrModified_.add(value);

        return this;
      }
      /**
       * <code>repeated .testtask.avast.budgetbuddy.utils.Transaction addedOrModified = 1;</code>
       */
      public Builder addAddedOrModified(
          int index, testtask.avast.budgetbuddy.utils.Proto.Transaction value) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureAddedOrModifiedIsMutable();
        addedOrModified_.add(index, value);

        return this;
      }
      /**
       * <code>repeated .testtask.avast.budgetbuddy.utils.Transaction addedOrModified = 1;</code>
       */
      public Builder addAddedOrModified(
          testtask.avast.budgetbuddy.utils.Proto.Transaction.Builder builderForValue) {
        ensureAddedOrModifiedIsMutable();
        addedOrModified_.add(builderForValue.build());

        return this;
      }
      /**
       * <code>repeated .testtask.avast.budgetbuddy.utils.Transaction addedOrModified = 1;</code>
       */
      public Builder addAddedOrModified(
          int index, testtask.avast.budgetbuddy.utils.Proto.Transaction.Builder builderForValue) {
        ensureAddedOrModifiedIsMutable();
        addedOrModified_.add(index, builderForValue.build());

        return this;
      }
      /**
       * <code>repeated .testtask.avast.budgetbuddy.utils.Transaction addedOrModified = 1;</code>
       */
      public Builder addAllAddedOrModified(
          java.lang.Iterable<? extends testtask.avast.budgetbuddy.utils.Proto.Transaction> values) {
        ensureAddedOrModifiedIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, addedOrModified_);

        return this;
      }
      /**
       * <code>repeated .testtask.avast.budgetbuddy.utils.Transaction addedOrModified = 1;</code>
       */
      public Builder clearAddedOrModified() {
        addedOrModified_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);

        return this;
      }
      /**
       * <code>repeated .testtask.avast.budgetbuddy.utils.Transaction addedOrModified = 1;</code>
       */
      public Builder removeAddedOrModified(int index) {
        ensureAddedOrModifiedIsMutable();
        addedOrModified_.remove(index);

        return this;
      }

      private long serverTimestamp_ ;
      /**
       * <code>optional int64 serverTimestamp = 2;</code>
       */
      public boolean hasServerTimestamp() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int64 serverTimestamp = 2;</code>
       */
      public long getServerTimestamp() {
        return serverTimestamp_;
      }
      /**
       * <code>optional int64 serverTimestamp = 2;</code>
       */
      public Builder setServerTimestamp(long value) {
        bitField0_ |= 0x00000002;
        serverTimestamp_ = value;
        
        return this;
      }
      /**
       * <code>optional int64 serverTimestamp = 2;</code>
       */
      public Builder clearServerTimestamp() {
        bitField0_ = (bitField0_ & ~0x00000002);
        serverTimestamp_ = 0L;
        
        return this;
      }

      // @@protoc_insertion_point(builder_scope:testtask.avast.budgetbuddy.utils.AccountDelta)
    }

    static {
      defaultInstance = new AccountDelta(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:testtask.avast.budgetbuddy.utils.AccountDelta)
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
